services:
  compiler:
    image: wingzzz2003/codeserver_ubuntu:beta
    pull_policy: always
    volumes:
      - ./${codeserverversion}/.config/code-server/config.yaml:/root/.config/code-server/config.yaml
      - ./${codeserverversion}/.local/share/code-server/User/settings.json:/root/.local/share/code-server/User/settings.json
      - sourcecode:/root/sourcecode
      - m2cache:/root/.m2
      - extensions:/root/.local/share/code-server/extensions/
    ports:
      - 9000:9000
    entrypoint: /root/entrypoint.sh

volumes:
  sourcecode:
  m2cache:
  extensions:
