services:
  compiler:
    image: wingzzz2003/codeserver_ubuntu:${codeserverversion}
    pull_policy: always
    restart: always
    volumes:
      - ./config-latest/.config/code-server/config.yaml:/home/ubuntu/.config/code-server/config.yaml
      - ./config-latest/.local/share/code-server/User/settings.json:/home/ubuntu/.local/share/code-server/User/settings.json
      - sourcecode:/home/ubuntu/sourcecode
      - m2cache:/home/ubuntu/.m2
      - extensions:/home/ubuntu/.local/share/code-server/extensions/
    ports:
      - 9000:9000
    entrypoint: /home/ubuntu/entrypoint.sh

volumes:
  sourcecode:
  m2cache:
  extensions:
