services:
  compiler:
    image: docker.io/wingzzz2003/codeserver_ubuntu:${codeserverversion}
    restart: always
    # group_add:
    #   - keep-groups
    volumes:
      # - ./config-latest/.config/code-server/config.yaml:/home/ubuntu/.config/code-server/config.yaml
      # - ./config-latest/.local/share/code-server/User/settings.json:/home/ubuntu/.local/share/code-server/User/settings.json
      - sourcecode:/home/ubuntu/sourcecode
      - m2cache:/home/ubuntu/.m2
      - extensions:/home/ubuntu/.local/share/code-server/extensions/
    network_mode: "host"
    entrypoint: /home/ubuntu/entrypoint.sh

volumes:
  sourcecode:
  m2cache:
  extensions:
